name: Docker Build and Push
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Étape 1: Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2: Configuration Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3: Connexion à Docker Hub (méthode sécurisée)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 4: Construction de l'image Docker
      - name: Build Docker image
        run: |
          docker build \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:latest \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:${{ github.sha }} \
            .

      # Étape 5: Push de l'image vers Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:${{ github.sha }}

      # Étape 6: Vérification (optionnelle)
      - name: Verify deployment
        run: |
          echo "Image successfully pushed to Docker Hub!"
          echo "Latest tag: ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:latest"
          echo "Commit tag: ${{ secrets.DOCKER_HUB_USERNAME }}/music-recommender:${{ github.sha }}"